// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:flutter_test/flutter_test.dart';
import 'package:simcrux/domain/models/sby_script.dart';

// The `.sby` job-file reader (VERIFICATION_GUIDE.md §18.3).
//
// It reads three facts — proof mode, depth and the task list — and
// deliberately understands nothing else. `sby` remains the authority on
// what a job file means; nothing here changes how a proof runs.

void main() {
  const bmc = '''
[options]
mode bmc
depth 20
append 0

[engines]
smtbmc boolector

[script]
read -formal democore.v
prep -top rvfi_testbench

[files]
democore.v
rvfi_macros.vh
''';

  group('options', () {
    test('mode and depth are read', () {
      final script = SbyScript.parse(bmc);
      expect(script.proofMode, 'bmc');
      expect(script.depth, 20);
      expect(script.tasks, isEmpty);
    });

    test('a timeout is read when the file sets one', () {
      expect(
        SbyScript.parse('[options]\nmode prove\ntimeout 900\n').timeoutSeconds,
        900,
      );
    });

    test('only the [options] section is consulted', () {
      // `depth` appearing in a script or a comment must not be mistaken
      // for the option.
      final script = SbyScript.parse('''
[options]
mode cover

[script]
depth 999
''');
      expect(script.proofMode, 'cover');
      expect(script.depth, isNull);
    });

    test('a task-scoped option still yields the unscoped default', () {
      final script = SbyScript.parse('''
[options]
mode bmc
deep: depth 40
''');
      expect(script.proofMode, 'bmc');
      expect(script.depth, 40);
    });

    test('comments and blank lines are ignored', () {
      final script = SbyScript.parse('''
# generated by genchecks.py

[options]
# the bound
mode bmc
depth 12
''');
      expect(script.depth, 12);
    });
  });

  group('tasks', () {
    test('a [tasks] section is enumerated in declaration order', () {
      final script = SbyScript.parse('''
[tasks]
basecase
induction

[options]
mode prove
''');
      expect(script.tasks, ['basecase', 'induction']);
    });

    test('only the first token of a task line names the task', () {
      expect(
        SbyScript.parse('[tasks]\nfast  small quick\nslow  large\n').tasks,
        ['fast', 'slow'],
      );
    });

    test('duplicates are collapsed', () {
      expect(SbyScript.parse('[tasks]\na\na\nb\n').tasks, ['a', 'b']);
    });
  });

  group('robustness', () {
    test('an empty or unusual file yields an all-null script, not a throw', () {
      expect(SbyScript.parse(''), const SbyScript());
      expect(SbyScript.parse('not a sby file at all'), const SbyScript());
    });

    test('a non-numeric depth is dropped rather than guessed at', () {
      expect(SbyScript.parse('[options]\ndepth lots\n').depth, isNull);
    });

    test('value semantics', () {
      expect(SbyScript.parse(bmc), SbyScript.parse(bmc));
      expect(SbyScript.parse(bmc).hashCode, SbyScript.parse(bmc).hashCode);
    });
  });
}
