// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;

import '../support/os_detritus.dart';

/// The orchestration corpus is self-enforcing: no loose fixture files
/// at `test/fixtures/orchestration/<scenario>/`. Every `simcrux.yaml`,
/// `behaviors.json`, and `expected_*.{ndjson,json}` lives under a
/// `generated/` directory (regenerated by
/// `tool/generate_orchestration_fixtures.dart`); only `helpers/README.md`
/// sits outside `generated/`. The same rule guards the `verification/`
/// release mirror.
void main() {
  const corpora = <String>[
    'test/fixtures/orchestration',
    'verification/fixtures/orchestration',
  ];

  for (final corpus in corpora) {
    test('$corpus: every fixture file lives under generated/', () {
      final root = Directory(corpus);
      if (!root.existsSync()) return; // nothing committed yet

      final offenders = <String>[];
      for (final entity in root.listSync(recursive: true)) {
        if (entity is! File) continue;
        // Opening the corpus in Finder is not a corpus defect.
        if (isOsDetritus(p.basename(entity.path))) continue;
        final rel = p.relative(entity.path, from: corpus);
        final segments = p.split(rel);
        // Allowed: <scenario>/generated/<file>, or helpers/<file>.
        final underGenerated = segments.contains('generated');
        final underHelpers = segments.first == 'helpers';
        if (!underGenerated && !underHelpers) {
          offenders.add(rel);
        }
      }

      expect(
        offenders,
        isEmpty,
        reason:
            'loose fixture files (must be under generated/): '
            '${offenders.join(', ')}',
      );
    });
  }
}
