// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:meta/meta.dart';
import 'package:simcrux/domain/models/test_spec.dart';

/// The request handed to `JobScheduler.submit`.
///
/// Carries the run-id (UUID generated by the caller), the tests to
/// execute, and the scheduling policy (concurrency, default timeout).
/// Pro-tier fields (`retryPolicy`, `remoteBackend`) are declared as
/// nullable here so the open-core scheduler can
/// ignore them and the Pro overlay can populate them via overrides.
@immutable
class RegressionRequest {
  /// Creates a [RegressionRequest].
  RegressionRequest({
    required this.runId,
    required List<TestSpec> tests,
    this.concurrency = 1,
    this.defaultTimeout = const Duration(seconds: 300),
  }) : tests = List<TestSpec>.unmodifiable(tests);

  /// Stable run identifier — generated by the caller, threaded into
  /// the `TestRun.id` the scheduler creates.
  final String runId;

  /// The flattened test specifications to execute.
  final List<TestSpec> tests;

  /// Maximum number of tests to run concurrently. The scheduler's
  /// semaphore-bounded pool honors this; resource-lock conflicts may
  /// further serialize within the bound.
  final int concurrency;

  /// Timeout applied to each test that does not declare its own
  /// `TestSpec.timeout`. The loader pushes the project-level default
  /// into each `TestSpec`, so this field is the scheduler-side
  /// fallback for tests that somehow arrive without one.
  final Duration defaultTimeout;

  /// Returns a copy with the given fields replaced.
  RegressionRequest copyWith({
    String? runId,
    List<TestSpec>? tests,
    int? concurrency,
    Duration? defaultTimeout,
  }) {
    return RegressionRequest(
      runId: runId ?? this.runId,
      tests: tests ?? this.tests,
      concurrency: concurrency ?? this.concurrency,
      defaultTimeout: defaultTimeout ?? this.defaultTimeout,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! RegressionRequest) return false;
    if (other.runId != runId) return false;
    if (other.concurrency != concurrency) return false;
    if (other.defaultTimeout != defaultTimeout) return false;
    if (other.tests.length != tests.length) return false;
    for (var i = 0; i < tests.length; i++) {
      if (other.tests[i] != tests[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    runId,
    Object.hashAll(tests),
    concurrency,
    defaultTimeout,
  );
}
