// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:meta/meta.dart';
import 'package:simcrux/domain/enums/hdl_language.dart';
import 'package:simcrux/domain/models/pass_fail_config.dart';
import 'package:simcrux/domain/models/resource_lock.dart';
import 'package:simcrux/domain/models/riscv_config.dart';
import 'package:simcrux/domain/models/waveform_policy.dart';

/// A single test, after defaults / suite / test inheritance has been
/// flattened by the config loader.
///
/// `TestSpec` is the immutable plan-of-record handed to the job
/// scheduler. Every parameterization sweep (`seeds: [1..50]`,
/// `parameters: {KEY: [a, b, c]}`) expands into N distinct `TestSpec`s
/// before scheduling, so the scheduler itself never needs to know
/// about templating.
///
/// Field shapes mirror the `simcrux.yaml` schema documented at
/// https://docs.simcrux.app/projects-and-simulators#schema, so a reader can move between
/// this file and that page without guessing.
@immutable
class TestSpec {
  /// Creates a [TestSpec].
  TestSpec({
    required this.id,
    required this.name,
    required this.suiteName,
    required this.simulatorId,
    required this.top,
    List<String>? sources,
    List<String>? includeDirs,
    Map<String, String>? defines,
    Map<String, String>? parameters,
    this.passFail = const ExitCodePassFailConfig(),
    this.waveform = const WaveformPolicy(),
    List<ResourceLock>? resources,
    this.timeout = const Duration(seconds: 300),
    Map<String, HdlLanguage>? sourceLanguages,
    this.seed,
    List<int>? seeds,
    Map<String, List<String>>? parameterSweeps,
    this.parentSpecId,
    this.riscv,
  }) : sources = List<String>.unmodifiable(sources ?? const []),
       includeDirs = List<String>.unmodifiable(includeDirs ?? const []),
       defines = Map<String, String>.unmodifiable(defines ?? const {}),
       parameters = Map<String, String>.unmodifiable(parameters ?? const {}),
       resources = List<ResourceLock>.unmodifiable(resources ?? const []),
       sourceLanguages = Map<String, HdlLanguage>.unmodifiable(
         sourceLanguages ?? const {},
       ),
       seeds = seeds == null ? null : List<int>.unmodifiable(seeds),
       parameterSweeps = parameterSweeps == null
           ? null
           : Map<String, List<String>>.unmodifiable(
               parameterSweeps.map(
                 (k, v) => MapEntry(k, List<String>.unmodifiable(v)),
               ),
             );

  /// Stable per-run identifier. Generated by the loader from
  /// `<suite>/<name>[+param=value...][+seed=N]`. Used as the
  /// `TestResult.testId`, the working-directory key, and the
  /// dashboard's row id.
  final String id;

  /// User-supplied test name (e.g. `alu_basic`). Not unique across
  /// suites — `[suiteName, name]` is; `id` carries the full flattened
  /// identity.
  final String name;

  /// Containing suite name (e.g. `cpu_unit`).
  final String suiteName;

  /// Simulator id this test should run under (`icarus`, `verilator`,
  /// `ghdl`, `cocotb`, …).
  final String simulatorId;

  /// HDL top-level module name (`tb_alu`, `tb_random`, …). Required
  /// for every simulator family SimCrux currently supports.
  final String top;

  /// Source files / globs to compile. Already resolved relative to
  /// the project root by the time this `TestSpec` exists.
  final List<String> sources;

  /// Include directories passed to the simulator (`+incdir+`,
  /// `-I`, …).
  final List<String> includeDirs;

  /// Verilog `+define+KEY=VALUE` / VHDL generic overrides.
  final Map<String, String> defines;

  /// Parameter overrides (`-pvalue`, etc.). For sweeps like
  /// `MEM_SIZE: [1024, 4096]`, each Cartesian combination becomes its
  /// own `TestSpec` with `parameters` carrying a single value.
  final Map<String, String> parameters;

  /// Pass/fail classifier configuration. Defaults to exit-code-based
  /// detection.
  final PassFailConfig passFail;

  /// Waveform-capture policy.
  final WaveformPolicy waveform;

  /// Resource locks the scheduler must hold for the duration of this
  /// test (e.g. `[fpga_board_0]` to serialize hardware-in-the-loop).
  final List<ResourceLock> resources;

  /// Per-test timeout. The scheduler escalates SIGTERM → SIGKILL on
  /// expiry.
  final Duration timeout;

  /// Explicit randomization seed for this test execution.
  ///
  /// When non-null, drivers are expected to thread this through to
  /// the simulator via the per-simulator seed CLI (`+seed=`, `-sv_seed`,
  /// `--seed`, …) so the run is deterministically reproducible. When
  /// null, the driver may either omit the seed (simulator default) or
  /// derive one from the system clock; in the latter case the actual
  /// seed used is captured in [TestResult.executionSeed] so the run
  /// can still be replayed.
  ///
  /// Seed expansion at the config-loader layer follows the same
  /// fan-out pattern as [parameters]: `seeds: [1, 2, 3]` in YAML
  /// becomes three distinct [TestSpec]s, each carrying one [seed]
  /// value in `id` and on this field. The scheduler itself never sees
  /// a multi-valued seed sweep — only fully-resolved specs.
  ///
  /// Pro-tier consumers (`FlakyRetryPolicy` in the Pro
  /// overlay) read this to retry a flaky test with the same seed on
  /// the first retry attempt (deterministic replay) and with a new
  /// seed on subsequent attempts (varied flakiness evidence).
  final int? seed;

  /// Pre-expansion seed sweep declaration (`seeds: [1, 2, 3]` in YAML).
  ///
  /// Populated by the config loader **only on un-expanded "template"
  /// specs**. After [TestSpecExpander.expandSpec] has fanned the spec
  /// out into N concrete instances, every child carries `seeds = null`
  /// and `seed = <one element>`.
  ///
  /// Null on a child spec means there was no seed sweep at this axis.
  /// A non-null but empty list is rejected by the parser (the gate
  /// requires at least one element).
  final List<int>? seeds;

  /// Pre-expansion parameter sweep declaration. Each map entry
  /// declares one sweep axis: the key is the parameter name (e.g.
  /// `MEM_SIZE`); the value is the list of values to sweep over (e.g.
  /// `[1024, 4096]`).
  ///
  /// Populated by the config loader **only on un-expanded "template"
  /// specs**. After expansion, every child spec carries
  /// `parameterSweeps = null` and a single-value
  /// [parameters] entry per swept axis.
  ///
  /// An empty/missing map means no parameter sweep at this axis;
  /// scalar `parameters: { MEM_SIZE: "1024" }` shorthand bypasses the
  /// expander entirely and lands directly in [parameters].
  final Map<String, List<String>>? parameterSweeps;

  /// On expanded child specs, the [id] of the un-expanded template
  /// spec that produced this child. Used by the Pro "Re-run all in
  /// this parameter group" workflow to re-issue every cartesian-
  /// product instance from a single parent.
  ///
  /// Null on un-expanded specs (the parent itself) and on specs that
  /// never had a sweep declared.
  final String? parentSpecId;

  /// The flattened `riscv:` block, or null
  /// for the overwhelming majority of tests that are not RISC-V
  /// architectural-compatibility runs.
  ///
  /// **A typed field, not a free-form map, and that cost is budgeted.**
  /// `TestSpec` has no extension slot, so carrying a
  /// per-test `riscv:` means this field plus its lines in [copyWith],
  /// [operator ==] and [hashCode] — all hand-written here — plus the
  /// **four** inheritance sites in the config loader (include file →
  /// project `defaults:` → suite → test; four levels, not three) plus
  /// `TestSpecExpander` propagation, which rides
  /// [copyWith] so a swept child keeps its `riscv:` config.
  ///
  /// **Never tier-gated**, here or anywhere downstream, including after
  /// `kBetaPeriod` flips — see the class doc on [RiscvConfig].
  final RiscvConfig? riscv;

  /// Explicit per-source language overrides. Keys are source paths
  /// (as they appear in [sources]); values are the user-declared
  /// [HdlLanguage].
  ///
  /// Used by the config loader's mixed-language compatibility check
  /// and by Cocotb's `TOPLEVEL_LANG` routing for non-conventional
  /// filenames. When a source path is absent from this map, the
  /// downstream consumer falls back to extension-driven detection via
  /// [HdlLanguageDetector].
  ///
  /// Empty for the common case where the user lets extensions speak
  /// for themselves.
  final Map<String, HdlLanguage> sourceLanguages;

  /// True when this spec carries a sweep declaration that the
  /// expander would fan out into multiple concrete instances.
  bool get isParameterized =>
      (seeds != null && seeds!.isNotEmpty) ||
      (parameterSweeps != null && parameterSweeps!.isNotEmpty);

  /// Human-readable display string that includes the bound seed and
  /// bound parameters when present. Used by the dashboard, the
  /// heatmap, and the re-run UI to disambiguate expanded children
  /// without relying on the synthesized [id].
  ///
  /// Format:
  /// - No seed, no parameters → `<suite>/<name>` (matches [id] for the
  ///   unparameterized base case).
  /// - Seed only → `<suite>/<name> [seed=7]`.
  /// - Parameters only → `<suite>/<name> [dataWidth=16, mode=fast]`.
  /// - Both → `<suite>/<name> [seed=7, dataWidth=16, mode=fast]`.
  ///
  /// Parameter ordering inside the brackets is alphabetical for
  /// stable display.
  String get displayName {
    final base = '$suiteName/$name';
    final parts = <String>[];
    if (seed != null) parts.add('seed=$seed');
    if (parameters.isNotEmpty) {
      final sorted = parameters.entries.toList()
        ..sort((a, b) => a.key.compareTo(b.key));
      for (final entry in sorted) {
        parts.add('${entry.key}=${entry.value}');
      }
    }
    if (parts.isEmpty) return base;
    return '$base [${parts.join(', ')}]';
  }

  /// Returns a copy with the given fields replaced.
  ///
  /// To clear an optional field on the returned copy, pass an
  /// explicit `null`-bearing sentinel via the matching `clear*` flag:
  /// `copyWith(clearSeeds: true)` produces a spec with `seeds = null`.
  /// Without the flag, a null argument is treated as "keep existing"
  /// per the standard [copyWith] convention.
  TestSpec copyWith({
    String? id,
    String? name,
    String? suiteName,
    String? simulatorId,
    String? top,
    List<String>? sources,
    List<String>? includeDirs,
    Map<String, String>? defines,
    Map<String, String>? parameters,
    PassFailConfig? passFail,
    WaveformPolicy? waveform,
    List<ResourceLock>? resources,
    Duration? timeout,
    Map<String, HdlLanguage>? sourceLanguages,
    int? seed,
    List<int>? seeds,
    Map<String, List<String>>? parameterSweeps,
    String? parentSpecId,
    RiscvConfig? riscv,
    bool clearSeeds = false,
    bool clearParameterSweeps = false,
  }) {
    return TestSpec(
      id: id ?? this.id,
      name: name ?? this.name,
      suiteName: suiteName ?? this.suiteName,
      simulatorId: simulatorId ?? this.simulatorId,
      top: top ?? this.top,
      sources: sources ?? this.sources,
      includeDirs: includeDirs ?? this.includeDirs,
      defines: defines ?? this.defines,
      parameters: parameters ?? this.parameters,
      passFail: passFail ?? this.passFail,
      waveform: waveform ?? this.waveform,
      resources: resources ?? this.resources,
      timeout: timeout ?? this.timeout,
      sourceLanguages: sourceLanguages ?? this.sourceLanguages,
      seed: seed ?? this.seed,
      seeds: clearSeeds ? null : (seeds ?? this.seeds),
      parameterSweeps: clearParameterSweeps
          ? null
          : (parameterSweeps ?? this.parameterSweeps),
      parentSpecId: parentSpecId ?? this.parentSpecId,
      // Carried through unconditionally so `TestSpecExpander`, which
      // materializes every swept child via copyWith, propagates the
      // `riscv:` block instead of silently dropping it.
      riscv: riscv ?? this.riscv,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! TestSpec) return false;
    return other.id == id &&
        other.name == name &&
        other.suiteName == suiteName &&
        other.simulatorId == simulatorId &&
        other.top == top &&
        _listEq(other.sources, sources) &&
        _listEq(other.includeDirs, includeDirs) &&
        _mapEq(other.defines, defines) &&
        _mapEq(other.parameters, parameters) &&
        other.passFail == passFail &&
        other.waveform == waveform &&
        _listEq(other.resources, resources) &&
        other.timeout == timeout &&
        _mapEq(other.sourceLanguages, sourceLanguages) &&
        other.seed == seed &&
        _nullableListEq(other.seeds, seeds) &&
        _nullableMapOfListEq(other.parameterSweeps, parameterSweeps) &&
        other.parentSpecId == parentSpecId &&
        other.riscv == riscv;
  }

  @override
  int get hashCode => Object.hash(
    id,
    name,
    suiteName,
    simulatorId,
    top,
    Object.hashAll(sources),
    Object.hashAll(includeDirs),
    Object.hashAllUnordered(
      defines.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    Object.hashAllUnordered(
      parameters.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    passFail,
    waveform,
    Object.hashAll(resources),
    timeout,
    Object.hashAllUnordered(
      sourceLanguages.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    seed,
    seeds == null ? null : Object.hashAll(seeds!),
    parameterSweeps == null
        ? null
        : Object.hashAllUnordered(
            parameterSweeps!.entries.map(
              (e) => Object.hash(e.key, Object.hashAll(e.value)),
            ),
          ),
    parentSpecId,
    riscv,
  );
}

bool _listEq<T>(List<T> a, List<T> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

bool _mapEq<K, V>(Map<K, V> a, Map<K, V> b) {
  if (a.length != b.length) return false;
  for (final entry in a.entries) {
    if (b[entry.key] != entry.value) return false;
  }
  return true;
}

bool _nullableListEq<T>(List<T>? a, List<T>? b) {
  if (identical(a, b)) return true;
  if (a == null || b == null) return false;
  return _listEq(a, b);
}

bool _nullableMapOfListEq<K, V>(Map<K, List<V>>? a, Map<K, List<V>>? b) {
  if (identical(a, b)) return true;
  if (a == null || b == null) return false;
  if (a.length != b.length) return false;
  for (final entry in a.entries) {
    final other = b[entry.key];
    if (other == null) return false;
    if (!_listEq(entry.value, other)) return false;
  }
  return true;
}
